repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0  # Match the version in your pyproject.toml
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Match the version in your pyproject.toml
    hooks:
      - id: isort
        language_version: python3.11

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: bash -c 'cd hasItPumped/backend && poetry run mypy .'
        language: system
        pass_filenames: false
        types: [python]