[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "solana_token_api"
version = "1.0.0"
description = "Solana Token Analysis API"
readme = "README.md"
requires-python = ">=3.8"

[project.optional-dependencies]
dev = [
    "pytest>=7.3.1",
    "black>=23.3.0",
    "flake8>=6.0.0",
    "isort>=5.12.0",
    "mypy>=1.3.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.pytest]
testpaths = ["tests"]