services:
  - type: web
    name: your-fastapi-backend
    env: python
    buildCommand: pip install poetry && poetry install --without dev
    startCommand: uvicorn src.solana_token_api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: POETRY_VERSION
        value: 1.7.1